services:

  api:
    build: .
    depends_on:
      - postgres
    environment:
      - POSTGRESQL_USER_FILE=/run/secrets/db_user
      - POSTGRESQL_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRESQL_DB_FILE=/run/secrets/db_name
      - POSTGRESQL_HOST_FILE=/run/secrets/db_host
      - POSTGRESQL_PORT=5432
    secrets:
      - db_user
      - db_password
      - db_name
      - db_host
    ports:
      - "5050:5050"
    networks:
      - local_network
    healthcheck:
      test: curl -f http://localhost:5050/  || exit 1
      start_period: 10s
    restart: always

  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USER_FILE=/run/secrets/db_user
      - POSTGRESQL_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRESQL_DB_FILE=/run/secrets/db_name
      - POSTGRESQL_HOST_FILE=/run/secrets/db_host
    secrets:
      - db_user
      - db_password
      - db_name
      - db_host
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/database/create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - "6000:5432"
    networks:
      - local_network
    restart: always

secrets:
  db_user:
    file: db_user.txt
  db_password:
    file: db_password.txt
  db_name:
    file: db_name.txt
  db_host:
    file: db_host.txt

volumes:
  postgres_data:


networks:
  local_network:
    driver: bridge
