services:

  api:
    build: .
    container_name: tomodachi-api
    depends_on:
      - postgres
    environment:
      - POSTGRESQL_USER_FILE=/run/secrets/db_user
      - POSTGRESQL_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRESQL_DB_FILE=/run/secrets/db_name
      - POSTGRESQL_HOST_FILE=/run/secrets/db_host
      - POSTGRESQL_PORT=5432
    secrets:
      - db_user
      - db_password
      - db_name
      - db_host
    ports:
      - "5050:5050"
    networks:
      - local_network
    healthcheck:
      test: curl -f http://localhost:5050/  || exit 1
      start_period: 10s
    restart: always

  postgres:
    image: bitnami/postgresql:latest
    container_name: tomodachi-postgres
    environment:
      - POSTGRESQL_USER_FILE=/run/secrets/db_user
      - POSTGRESQL_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRESQL_DB_FILE=/run/secrets/db_name
      - POSTGRESQL_HOST_FILE=/run/secrets/db_host
    secrets:
      - db_user
      - db_password
      - db_name
      - db_host
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/scripts/migrations/create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - "6000:5432"
    networks:
      - local_network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: tomodachi-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_USERNAME: daimao
      PGADMIN_DEFAULT_PASSWORD: finalfantasyvi
    ports:
      - "7070:80"
    depends_on:
      - postgres
    networks:
      - local_network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

secrets:
  db_user:
    file: db_user.txt
  db_password:
    file: db_password.txt
  db_name:
    file: db_name.txt
  db_host:
    file: db_host.txt

volumes:
  postgres_data:
  pgadmin-data:


networks:
  local_network:
    driver: bridge
