/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Tomodachi API
 * API for managing hubs in the Tomodachi application.
 * OpenAPI spec version: 1.0.0
 */
import type { LimitParameter } from './limitParameter';
import type { OffsetParameter } from './offsetParameter';

export type GetHubsParams = {
/**
 * Maximum number of items to return
 */
limit?: LimitParameter;
/**
 * Offset for pagination
 */
offset?: OffsetParameter;
};
