/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Tomodachi API
 * API for managing hubs in the Tomodachi application.
 * OpenAPI spec version: 1.0.0
 */
import type { Hub } from './hub';

/**
 * Response with a single Hub object
 */
export type SingleHubResponseResponse = Hub;
